/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arthur
 */
public class Payement extends javax.swing.JFrame {

    //creation d'un objet privé de Fentre 
    private Fenetre mafenetre = new Fenetre(false);
    String u, s;
    double prix;
    int i;

    /**
     * Creates new form Payement Constructeur de la Jframe de payement
     *
     * @param username
     * @param p
     * @param seance
     * @param id
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public Payement(String username, double p, String seance, int id) throws SQLException, ClassNotFoundException {
        initComponents();
        //affichage du prix à payer
        jLabel2.setText("" + p + " €");
        //si c'est un membre, affichage de sa balance 
        if (!username.equals("guest")) {
            jLabel6.setText("" + mafenetre.balance(username) + " €");
        } //si c'est un visiteur, affichage du message suivant
        else if (username.equals("guest")) {
            jLabel6.setText("vous n'avez pas de compte chez nous");
        }

        u = username;
        prix = p;
        s = seance;
        i = id;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("A payer");

        jLabel2.setText("jLabel2");

        jLabel3.setText("CardNo");

        jLabel4.setText("CVC");

        jLabel5.setText("Balance :");

        jLabel6.setText("jLabel6");

        jButton1.setText("Payer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bouton permettant de valider le payement 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String CardNo = jTextField1.getText();
        int CVC = Integer.parseInt(jTextField2.getText());
        int id = 0;
        int g = 0;
        id = (int) (1 + (Math.random() * (999 - 1)));
        g = (int) (1 + (Math.random() * (999 - 1)));

        //comparaison entre le montant de la balance et le montant à payer
        try {
            //si balance trop faible il faut ajouter de l'argent à la balance
            if (!u.equals("guest") && ((mafenetre.balance(u) == 0) || ((mafenetre.balance(u) - prix) < 0))) {

                JOptionPane.showMessageDialog(this, "balance trop faible. Veuillez renflouer la balance");
                new ajoutbal(u, prix, s, i).setVisible(true);
                this.dispose();
            } //si le client est un visiteur , validation du payement sans se soucier de la balance car il n'a aucun compte dans le cinema
            else if (u.equals("guest")) {
                JOptionPane.showMessageDialog(this, "Payement successfull");
                try {
                    mafenetre.Ticket(id, String.valueOf(g), i, prix, s);
                    new Ticket(id).setVisible(true);
                    this.dispose();

                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Payement.class.getName()).log(Level.SEVERE, null, ex);
                }
            } //verification que les champs de crate bancaire soient bien remplis
            else if (CardNo.equals("") && CVC == 0) {

                JOptionPane.showMessageDialog(this, "enter CardNo and CVC");

            } else if (!(CardNo.equals("")) && CVC == 0) {

                JOptionPane.showMessageDialog(this, "enter CVC");
            } else if ((CardNo.equals("")) && !(CVC == 0)) {

                JOptionPane.showMessageDialog(this, "enter CardNo");
            } else try {
                //si le client est membre et que les données bancaires sont nous pouvons approuver le payelent,créer le ticket et mettre à jour la balance du membre
                if (mafenetre.vcard(u, CardNo, CVC) == true) {

                    JOptionPane.showMessageDialog(this, "Payement successfull");

                    mafenetre.Ticket(id, u, i, prix, s);
                    mafenetre.updatePrice(prix, u);
                    new Ticket(id).setVisible(true);
                    this.dispose();

                } //Si non afficher Wrong et recommencer à saisir les données de CB
                else if (mafenetre.vcard(u, CardNo, CVC) == false) {

                    JOptionPane.showMessageDialog(this, "wrong CardNo or CVC");
                }
            } catch (SQLException ex) {
                Logger.getLogger(connexionframe.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Payement.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Payement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
